services:
  postgres:
    image: postgres:15-alpine
    container_name: bugtracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bugtracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bugtracker-network

  adminer:
    image: adminer:4.8.1
    container_name: bugtracker-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - bugtracker-network
    depends_on:
      - postgres

  app:
    build: .
    container_name: bugtracker-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=bugtracker
      - SEED_DEFAULT_ADMIN=false
      - JWT_SECRET=dev_secret
    depends_on:
      - postgres
    networks:
      - bugtracker-network
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./nest-cli.json:/app/nest-cli.json
    command: npm run start:dev

volumes:
  postgres_data:

networks:
  bugtracker-network:
    driver: bridge
